spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url:  jdbc:p6spy:mysql://${DB_HOST:10.0.0.103}:${DB_PORT:3306}/${DB_DATABASE:db_saas_manager}?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8