spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url:  jdbc:p6spy:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:db}?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8