insert into `v2_saas_privileges` (`resource`, `operation`, `resource_zh`) values
('overview', 'create', '总览'),
('overview', 'retrieve', '总览'),
('overview', 'update', '总览'),
('overview', 'delete', '总览'),
('overview', 'review', '总览'),

('data_center', 'create', '数据中心'),
('data_center', 'retrieve', '数据中心'),
('data_center', 'update', '数据中心'),
('data_center', 'delete', '数据中心'),
('data_center', 'review', '数据中心'),

('personnel_info', 'create', '人员信息'),
('personnel_info', 'retrieve', '人员信息'),
('personnel_info', 'update', '人员信息'),
('personnel_info', 'delete', '人员信息'),
('personnel_info', 'review', '人员信息'),

('housing', 'create', '房屋管理'),
('housing', 'retrieve', '房屋管理'),
('housing', 'update', '房屋管理'),
('housing', 'delete', '房屋管理'),
('housing', 'review', '房屋管理'),

('contract', 'create', '合同管理'),
('contract', 'retrieve', '合同管理'),
('contract', 'update', '合同管理'),
('contract', 'delete', '合同管理'),
('contract', 'review', '合同管理'),

('resident_entry', 'create', '出入管理'),
('resident_entry', 'retrieve', '出入管理'),
('resident_entry', 'update', '出入管理'),
('resident_entry', 'delete', '出入管理'),
('resident_entry', 'review', '出入管理'),

('capture', 'create', '抓拍记录'),
('capture', 'retrieve', '抓拍记录'),
('capture', 'update', '抓拍记录'),
('capture', 'delete', '抓拍记录'),
('capture', 'review', '抓拍记录'),

('immigration', 'create', '迁入迁出管理'),
('immigration', 'retrieve', '迁入迁出管理'),
('immigration', 'update', '迁入迁出管理'),
('immigration', 'delete', '迁入迁出管理'),
('immigration', 'review', '迁入迁出管理'),

('vehicle_info', 'create', '车辆信息'),
('vehicle_info', 'retrieve', '车辆信息'),
('vehicle_info', 'update', '车辆信息'),
('vehicle_info', 'delete', '车辆信息'),
('vehicle_info', 'review', '车辆信息'),

('vehicle_entry', 'create', '出入管理'),
('vehicle_entry', 'retrieve', '出入管理'),
('vehicle_entry', 'update', '出入管理'),
('vehicle_entry', 'delete', '出入管理'),
('vehicle_entry', 'review', '出入管理'),

('person_control', 'create', '人员布控'),
('person_control', 'retrieve', '人员布控'),
('person_control', 'update', '人员布控'),
('person_control', 'delete', '人员布控'),
('person_control', 'review', '人员布控'),

('vehicle_control', 'create', '车辆布控'),
('vehicle_control', 'retrieve', '车辆布控'),
('vehicle_control', 'update', '车辆布控'),
('vehicle_control', 'delete', '车辆布控'),
('vehicle_control', 'review', '车辆布控'),

('work_entry', 'create', '工单列表'),
('work_entry', 'retrieve', '工单列表'),
('work_entry', 'update', '工单列表'),
('work_entry', 'delete', '工单列表'),
('work_entry', 'review', '工单列表'),

('customer_service', 'create', '智能微客服'),
('customer_service', 'retrieve', '智能微客服'),
('customer_service', 'update', '智能微客服'),
('customer_service', 'delete', '智能微客服'),
('customer_service', 'review', '智能微客服'),

('patrol', 'create', '智能巡更'),
('patrol', 'retrieve', '智能巡更'),
('patrol', 'update', '智能巡更'),
('patrol', 'delete', '智能巡更'),
('patrol', 'review', '智能巡更'),

('assessment', 'create', '考核管理'),
('assessment', 'retrieve', '考核管理'),
('assessment', 'update', '考核管理'),
('assessment', 'delete', '考核管理'),
('assessment', 'review', '考核管理'),

('attendance', 'create', '考勤管理'),
('attendance', 'retrieve', '考勤管理'),
('attendance', 'update', '考勤管理'),
('attendance', 'delete', '考勤管理'),
('attendance', 'review', '考勤管理'),

('device', 'create', '设备管理'),
('device', 'retrieve', '设备管理'),
('device', 'update', '设备管理'),
('device', 'delete', '设备管理'),
('device', 'review', '设备管理'),

('system', 'create', '系统管理'),
('system', 'retrieve', '系统管理'),
('system', 'update', '系统管理'),
('system', 'delete', '系统管理'),
('system', 'review', '系统管理'),

('work_entry_rule', 'create', '工单规则管理'),
('work_entry_rule', 'retrieve', '工单规则管理'),
('work_entry_rule', 'update', '工单规则管理'),
('work_entry_rule', 'delete', '工单规则管理'),
('work_entry_rule', 'review', '工单规则管理'),

('person_privilege', 'create', '人员权限管理'),
('person_privilege', 'retrieve', '人员权限管理'),
('person_privilege', 'update', '人员权限管理'),
('person_privilege', 'delete', '人员权限管理'),
('person_privilege', 'review', '人员权限管理'),

('entry_privilege', 'create', '通行权限组管理'),
('entry_privilege', 'retrieve', '通行权限组管理'),
('entry_privilege', 'update', '通行权限组管理'),
('entry_privilege', 'delete', '通行权限组管理'),
('entry_privilege', 'review', '通行权限组管理'),

('failure_positioning', 'create', '失败原因定位'),
('failure_positioning', 'retrieve', '失败原因定位'),
('failure_positioning', 'update', '失败原因定位'),
('failure_positioning', 'delete', '失败原因定位'),
('failure_positioning', 'review', '失败原因定位'),

('comm_action_saas', 'create', '居民功能后台'),
('comm_action_saas', 'retrieve', '居民功能后台'),
('comm_action_saas', 'update', '居民功能后台'),
('comm_action_saas', 'delete', '居民功能后台'),
('comm_action_saas', 'review', '居民功能后台'),

('sensitive_info', 'create', '敏感信息'),
('sensitive_info', 'retrieve', '敏感信息'),
('sensitive_info', 'update', '敏感信息'),
('sensitive_info', 'delete', '敏感信息'),
('sensitive_info', 'review', '敏感信息'),

('garbage_classification', 'create', '垃圾分类'),
('garbage_classification', 'retrieve', '垃圾分类'),
('garbage_classification', 'update', '垃圾分类'),
('garbage_classification', 'delete', '垃圾分类'),
('garbage_classification', 'review', '垃圾分类'),

('focuses', 'create', '重点人员'),
('focuses', 'retrieve', '重点人员'),
('focuses', 'update', '重点人员'),
('focuses', 'delete', '重点人员'),
('focuses', 'review', '重点人员'),

('epidemic', 'create', '疫情防控'),
('epidemic', 'retrieve', '疫情防控'),
('epidemic', 'update', '疫情防控'),
('epidemic', 'delete', '疫情防控'),
('epidemic', 'review', '疫情防控'),

('runway', 'create', '智慧跑道'),
('runway', 'retrieve', '智慧跑道'),
('runway', 'update', '智慧跑道'),
('runway', 'delete', '智慧跑道'),
('runway', 'review', '智慧跑道'),

('resident_rule', 'create', '居民公约'),
('resident_rule', 'retrieve', '居民公约'),
('resident_rule', 'update', '居民公约'),
('resident_rule', 'delete', '居民公约'),
('resident_rule', 'review', '居民公约')
;

